### ISSUE TITLE
Switch places with official repository

### ISSUE THREAD

**Issue by techtonik** [palazzol/PDCurses#3]
It is inconvenient to send pull requests to https://github.com/wmcbrine/PDCurses because it is forked from this one and by default GitHub proposes to sent PR here.

**Comment by palazzol** [comment]
Let me know what I should do to make this happen.  Should I just delete this repository and refork it?

**Comment by techtonik** [comment]
Deleting repository may work - https://help.github.com/articles/what-happens-to-forks-when-a-repository-is-deleted-or-changes-visibility/

**Comment by palazzol** [comment]
I put in an official request for help from github with this, and I'm also asking the mailing list.

**Comment by palazzol** [comment]
I asked github to do this and it looks like they did!

**Comment by techtonik** [comment]
Yes. Awesome!
